name: head-hunter
channels:
- conda-forge
dependencies:
- python==3.8
- ipython>=8
- pip>=22
- pre-commit
- black
- isort
- mypy
- jupyterlab>=3
- jupyterlab_code_formatter
- pyperclip
- mkdocs
- mkdocstrings
- mkdocstrings-python
- mkdocs-literate-nav
- mkdocs-gen-files
- mkdocs-jupyter
- pip:
  - mkdocs-windmill
  - mkdocs-section-index
