name: head-hunter
channels:
- conda-forge
dependencies:
- python==3.10
- ipython>=8
- pip>=24
- requests
- pre-commit
- black
- isort
- mypy
- types-requests
- jupyterlab>=3
- jupyterlab_code_formatter
- pyperclip
- mkdocs
- mkdocstrings
- mkdocstrings-python
- mkdocs-literate-nav
- mkdocs-gen-files
- mkdocs-jupyter
- pip:
  - mkdocs-windmill
  - mkdocs-section-index
